language: ruby
# only run CI-builds on master branch
branches:
  only:
  - main
rvm:
- 2.7.2
# set execution permission on our build script
before_script:
 - chmod +x ./script/cibuild.sh
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild.sh
exclude: [vendor]
sudo: false
